
= Exchange Header Envelope (XHE)

The Exchange header envelope (XHE) describes either:

* a header as an integrated part of a business document, or
* an envelope as a transport for the business documents,

of payloads of one or more business documents. The main idea with XHE is to describe the
main information about the payloads (as catalogue) to the sender and receiver.

Benefit of using XHE:
. routing of business documents,
. simplifying the bundling of several business documents and support document into one package,
. simplifies the processing of business documents.

Read more about Exchange Header Envelope
link:https://docs.oasis-open.org/bdxr/xhe/v1.0/cs02/xhe-v1.0-cs02-oasis.html#S-HEADER-AND-ENVELOPE-INFORMATION[here].


== Header envelope Information

The metadata information about the Exchange Header Envelope need to be provided, i.e XHE version identifier,
Specification identifier, Business process type identifier, Header information and Payload information.
Note that all namespaces need to be provided before the header envelope information.

.Example of how to implement the general (head) information in XHE.
[source, xml, indent=0]
----
include::../{snippet-dir}/xhe-example.xml[tags=general-information]
----
<1> XHE version number
<2> XHE specification identifier (`CustomizationID`)
<3> XHE business process type identifier (`ProfileID`)
<4> Header information
<5> Payloads - information about each relevant payload


== Header Information

Information relevant to the header envelope need to be provided in element `xha:Header`, and will be used
to handle the envelope. The header envelope contains information about the business scope, where contracting
authority can specify the criterion of the scope of business.

.Example of how to implement the header-information in XHE.
[source, xml, indent=0]
----
include::../{snippet-dir}/xhe-example.xml[tags=header]
----
<1> Identifier
<2> Unique universal identifier (UUID), recommend version 4.
<3> Date and time for when this header/envelope was created.
<4> Business scope
<5> The property of the business scope
<6> The value of the property


== Payload Information

Information about the set of payloads within the envelope need to be provided in element `xha:Payloads`, and
information about the specific payload need to be provided in element `xha:Payload`.
For example, the payload instance can be EHF Pre-award request, EHF Billing 3.0, or other tender documents.

.Example of how to implement the payloads in XHE.
[source, xml, indent=0]
----
include::../{snippet-dir}/xhe-example.xml[tags=payloads]
----
<1> Information about the specific payload instance
<2> Identification of the specific payload instance
<3> Description of the specific payload instance
<4> Payload instance's customization identifier
<5> Payload instance's profile identifier
<6> Payload instance is not encrypted- always use `False`









