
=== Use Case 1

****

Description::
This use case illustrates the use of document folders in DPS between Central Purchasing Body and the
Contracting Authrities connected to Central Purcahsing Body.


Parties involved::
Contracting Authority +
Central Purchasing body

Assumptions::
. Central Purchasing Boy has created an DPS for hotel services.

Flow::
. Central Purchasing system sends a document folder with a catalogue template to the Contracting Authorities.
. The Contracting Authorities receives a Document Folder with a catalogue template, and saves the tender
document in the tender system.
. The Contracting Authorities Tender system sends a confirmation to the Central Purchasing system.
. The Central Purchasing system receives the message and store the information.


Result::
. The Contracting Authorities receives a document folder with a catalogue template from the Central
Purchasing system.
. The Central Purchasing body sends EHF Document Folder to Contracting Authorities when:
.. creating DPS,
.. updating tender documents inside the EHF Document Folder.
. The Central Purchasing Body can also send EHF Document Folder to new suppliers that qualifies to DPS.



****