= Introduction

The EHF Get Evidence is intended to be used by contracting authorities to request supporting documents, both from economic operators (EO) and official database(s). The supporting documents to be retrieved from the official database can be both unrestricted and restricted.

The scope of the first phase of this project is to request supporting documents for Norwegian EOs from the Norwegian Tax Authorities (Skatteetaten) and Brønnøysund Registry Centre (Brønnøysundregistrene).


== Scope of this document

This document explains and illustrates how to implement XML documents based on specific requirements in the Norwegian marked (EHF specific rules and restrictions). The GetEvidence data model is rich and flexible enough to allow use both for contracts above and below threshold. However this document is oriented exclusively to illustrate how to request evidences for contracts above the threshold.

===  Out-of-Scope

Many of the requirements and recommendations expressed in this document MAY NOT be valid for contracts below the threshold. However, from a purely technical point of view, this document MAY be used to understand how the data model works, and to create, in a normalized way, XML instances containing evidence request and response for contracts below the threshold.
